# ubuntu
- name: Add Ondrej PHP PPA
  apt_repository:
    repo: "{{ PHP_VERSION_ONDREJ }}"
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: php74 install
  apt: 
    name: "{{ item }}"
    state: present
  loop:
    - php7.4-fpm
    - php7.4-mysql
  when: ansible_facts['os_family'] == "Debian"

# centos
- name: Add EPEL repository for CentOS 7
  yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '7'

- name: Add Remi repository for PHP 7.4 on CentOS 7
  yum_repository:
    name: remi-php74
    description: Remi's PHP 7.4 repository
    baseurl: http://rpms.remirepo.net/enterprise/7/php74/$basearch/
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '7'

- name: PHP 7.4 install on CentOS 7
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - php74-php-fpm
    - php74-php-mysqlnd
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '7'

# 共通
- name: Start PHP-FPM service
  systemd:
    name: php7.4-fpm
    state: started
    enabled: yes

- name: copy php.ini
  copy:
    src: "roles/install_php7.4/files/{{ item.src }}"
    dest: "/etc/php/7.4/cli/{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "php.ini", dest: . }

- name: copy www.conf
  copy:
    src: "roles/install_php7.4/files/{{ item.src }}"
    dest: "/etc/php/7.4/fpm/pool.d/{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "pool.d/www.conf", dest: . }
  notify: restart php-fpm
