# mysql設定
- name: Create wp_db
  mysql_db:
    login_user: "{{ admin_user_name }}"
    login_password: "{{ admin_user_password }}"
    name: wp_db
    state: present
    collation: utf8_bin

- name: Add wp-user
  mysql_user:
    login_user: "{{ admin_user_name }}"
    login_password: "{{ admin_user_password }}"
    name: "{{wp_user_name}}"
    host: '%'
    password: "{{wp_user_password}}"
    priv: "wp_db.*:ALL"
    state: present

- name: Grant PROCESS privilege to root
  mysql_user:
    login_password: "{{ admin_user_password }}"
    name: "{{ admin_user_name }}"
    host: '%'
    priv: "*.*:PROCESS"
    state: present

# WordPressのインストール
- name: copy wordpress
  copy:
    src: "roles/install_wordpress/files/wordpress-6.4.2.tar.gz"
    dest: /tmp/wordpress-6.4.2.tar.gz
    backup: no
    owner: root
    group: root

- name: wordpress expansion
  unarchive: 
    src: /tmp/wordpress-6.4.2.tar.gz
    dest: /var/www/html/ 
    copy: no

- name: change of ownership of wordpress
  file: 
    path: /var/www/html/wordpress/ 
    owner: www-data 
    group: www-data 
    recurse: yes
