# ubuntu
- name: Add deadsnakes PPA for Python 3.10 on Ubuntu
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Python 3.10 on Ubuntu
  apt:
    name: python3.10
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install required packages for Ubuntu
  apt:
    name: "{{ item.pkg }}"
    state: present
  loop:
    - { pkg: pkg-config }
    - { pkg: libmysqlclient-dev }
    - { pkg: python3-pip }
  when: ansible_facts['os_family'] == "Debian"

# centos
- name: Add EPEL repository for CentOS 7
  yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '7'

- name: Install Python 3.10 on CentOS 7
  yum:
    name: python310
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '7'

- name: Install required packages for CentOS 7
  yum:
    name: "{{ item.pkg }}"
    state: present
  loop:
    - { pkg: pkgconfig }
    - { pkg: mysql-devel }
    - { pkg: python3-pip }
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '7'
