# Create user
- name: Create user
  user:
    name: "{{item.user}}"
    createhome: yes
    shell: /bin/bash
  with_items:
    - { user: 'user01'}

# ユーザにSUDO権限を追加する
- name: add sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "{{ item.match }}"
    line: "{{ item.line }}"
  loop:
  - { match: 'user01', line: 'user01 ALL=(ALL) NOPASSWD: ALL' }

# 作成ユーザの~/.sshディレクトリにssh接続用のキーを格納する
- name: add authorized_key
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ lookup('file', item.ssh) }}"
  loop:
  - { user: 'user01', ssh: 'roles/create_user/files/user01/authorized_key'}
